loot-table:
  "Day 1":
    items:
      - material: OAK_PLANKS
        amount: 64
  "Day 2":
    items:
      - material: COPPER_INGOT
        amount: 32
  "Day 3":
    items:
      - material: IRON_INGOT
        amount: 16
  "Day 4":
    items:
      - material: GOLD_INGOT
        amount: 8
  "Day 5":
    items:
      - material: IRON_INGOT
        amount: 16
  "Day 6":
    items:
        - material: OBSIDIAN
          amount: 64
        - material: DIAMOND
          amount: 8
  "Day 7":
    items:
      - material: NETHERITE_INGOT
        amount: 1
